### ISSUE TITLE
relating to "Preview Element".

### ISSUE THREAD

**Issue by bunjii** [CSDG-DDL/PTK#63]
1. when I open the file (attached below), karamba part won't work and some strange behavior in the preview occurs.

2. when I switched off the structural assembly and recompute, truss upper & lower chords appear in place but extension parts remain.

3. when I tweak an arbitrary part, extensions disappear.

**Comment by bunjii** [comment]
![when-file-is-opened](https://user-images.githubusercontent.com/16072693/50878896-39085d00-141c-11e9-8acd-3de19bbdd372.PNG)
![when-structural-assemble-switched-off-and-recompute](https://user-images.githubusercontent.com/16072693/50878897-39a0f380-141c-11e9-9e3a-716728bf7d70.PNG)
![when-arbitral-part-is-disconnected](https://user-images.githubusercontent.com/16072693/50878898-39a0f380-141c-11e9-8b63-8519a5ae9956.PNG)
[files.zip](https://github.com/CSDG-DDL/PTK/files/2739495/files.zip)

**Comment by TodaYuto** [comment]
There was a part that operated and inverted BaceCurve of Element whose "DetailClass" is a higher class, so I fixed it.
ElementClass' s BaseCurve is set to "private", but since we can call CurveClass's Reverse () method, we may need to do a deep copy on get.
I pushed these changes to feature_bugfixPrevElem

**Comment by bunjii** [comment]
thanks!
